# Generated by Django 4.2.11 on 2024-05-12 12:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.CharField(max_length=1500)),
                ("date_start", models.DateField(default=datetime.date.today)),
                ("date_end", models.DateField(default=datetime.date.today)),
                ("status", models.BooleanField(default=True)),
                (
                    "admins",
                    models.ManyToManyField(
                        related_name="project_admins", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="project_users", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.CharField(max_length=1500)),
                ("date_start", models.DateField(default=datetime.date.today)),
                ("date_end", models.DateField(default=datetime.date.today)),
                ("status", models.BooleanField(default=True)),
                ("color", models.CharField(default="#000000", max_length=7)),
                (
                    "assigned_users",
                    models.ManyToManyField(
                        related_name="task_users", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
