# Generated by Django 4.2.11 on 2024-05-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_projectinvitation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
